name: Build and Publish Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'VTK Version'
        required: false
        default: "9.2.6"
      variant:
        description: 'Variant'
        required: false
        default: "osmesa"
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' ||
        ( github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        )
    steps:
      - uses: actions/checkout@v4

      - name: Log into the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: token
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for the Slim Docker image
        id: slim_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            suffix=-slim,onlatest=true
      - name: Build and push the Slim Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.slim_meta.outputs.tags }}
          labels: ${{ steps.slim_meta.outputs.labels }}
          build-args: |
            VTK_VERSION=${{ github.event.inputs.version }}
            VTK_VARIANT=${{ github.event.inputs.variant }}
